### ISSUE TITLE
Unable to fetch jar from bintray

### ISSUE THREAD

**Issue by kartikarora** [saantiaguilera/gradle-api-easy_publish#8]
### Description

I did the configuration for my library, setup everything in the root `build.gradle` file, added the classpath and the plugin. When I run gradle sync, I get this as the error:

```
Error:Could not find com.saantiaguilera.gradle.publish.helper:core:2.0.2.
Searched in the following locations:
    https://jcenter.bintray.com/com/saantiaguilera/gradle/publish/helper/core/2.0.2/core-2.0.2.pom
    https://jcenter.bintray.com/com/saantiaguilera/gradle/publish/helper/core/2.0.2/core-2.0.2.jar
Required by:
    :library:unspecified
```

### Additional Information

* Dependency version: 2.0.2
* Dependencies used: `com.saantiaguilera.gradle.publish.helper:core:2.0.2`
* Gradle version: Gradle 2.14.1, Gradle plugin : 2.3.3

**Comment by kartikarora** [comment]
Also, I cannot see this plugin's directory when I open http://jcenter.bintray.com/com/saantiaguilera/. Could it be a publishing issue?

**Comment by saantiaguilera** [comment]
Bintray hasnt added it to jcenter yet 😕 Add this in your buildscript repositories lookup urls for now and it should find it!

```
buildscript {
    repositories {
        // This from below
        maven {
            url 'https://dl.bintray.com/saantiaguilera/maven/'
        }
    }
}
```

**Comment by saantiaguilera** [comment]
Im seeing it inside bintray, check if you can see this http://jcenter.bintray.com/com/saantiaguilera/gradle/publish/helper/core/2.0.2/

**Comment by saantiaguilera** [comment]
I've just received the confirmation from bintray adding it to jcenter, so you dont even need it now the maven url, could you try again if it can find it? (just having `jcenter()` in your buildscripts repostories should be  enough). Im using it like this in another repo:
```gradle
apply plugin: 'com.saantiaguilera.gradle.publish.helper'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'

        classpath "com.saantiaguilera.gradle.publish.helper:core:2.0.2"

        classpath("com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3")
        classpath("com.github.dcendents:android-maven-gradle-plugin:1.5")
    }
}

...
```

**Comment by kartikarora** [comment]
Yep, it seems to be resolving now. But I'm getting `Error:(1, 0) Plugin with id 'com.jfrog.bintray' not found.` now in my module's `build.gradle` @saantiaguilera

**Comment by saantiaguilera** [comment]
Do you have bintray and maven plugins?
```
    classpath("com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3")
    classpath("com.github.dcendents:android-maven-gradle-plugin:1.5")
```
No need to apply them tho, im doing it inside :)

**Comment by kartikarora** [comment]
Nope, I don't. I did earlier.

**Comment by saantiaguilera** [comment]
Oh, I'm adding it to the readme then for future cases!

Tell me if it works when adding both classpaths :)

**Comment by kartikarora** [comment]
Ah yes! Gradle synced without errors! Thanks a lot! :)

Quick question, adding the `apiKey` and the `user` in my `.bashrc` as environment variables should work right?

**Comment by saantiaguilera** [comment]
If you use bash in the terminal (and not zsh or some other shell) it will! For example, I use zsh so I've them in `.zshrc`

Access them in gradle via `System.getenv('EXPORTED_VAR')` and it should find it :)

**Comment by kartikarora** [comment]
I am using `zsh`, have put them in `.zshrc`. bintray user is my username, I assume. Do I need to put module specific configurations if I have just 1 module and the global configurations setup?

**Comment by kartikarora** [comment]
I'm getting this now `Could not get unknown property 'publishModule' for task set`. On running `./gradlew publishModules` at project root. 

Apologies if these queries seem irritating.

**Comment by kartikarora** [comment]
Ah nevermind. All done. Publishes successfully! 

Thanks a lot for this plugin! :)

**Comment by saantiaguilera** [comment]
Haha, sorry for the delay.

- `I am using zsh, have put them in .zshrc. bintray user is my username, I assume. Do I need to put module specific configurations if I have just 1 module and the global configurations setup?` -> No need, you can use the global if you want. Whatever you find it more clean
- `I'm getting this now Could not get unknown property 'publishModule' for task set. On running ./gradlew publishModules at project root. Apologies if these queries seem irritating.` I would guess you havent defined a `publishOrder = [ 'your_single_module' ]` if you are planning on using the global task. You can use `./gradlew your_single_module:publishModule` if you dont want to define the publish order.

I guess I can make it optional the order if its just 1 module. I will try to add it when im free :D

Glad it worked!
